language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"

env:
  - FLASK=0.9
  - FLASK=0.10

branches:
  only:
    - master

install: 
  - pip install -q Flask==$FLASK --use-mirrors --quiet

script: 
  - python setup.py test
  - python flask_jsonrpc_tests.py