language: python

python:
  - "2.6"
  - "2.7"

env:
  - FLASK_ENV=TESTING FLASK=0.9
  - FLASK_ENV=TESTING FLASK=0.10

install: 
  - pip install -q Flask==$FLASK --use-mirrors --quiet

script: 
  - python setup.py test
  - python flask_jsonrpc_tests.py